# Site settings
title: 隐夜涯的自留地
SEOTitle: 隐夜涯的自留地 | Yinyeya Blog
header-img: img/home-bg.jpg
email: yinyeya@gmail.com
description: "生物医学狗的非典型日常 | fake生信撸码猿 | 跟着大佬瞎搞薅羊毛 | 胡整瞎搞全都要 | 外面的世界看着精彩实则无奈"
keyword: "隐夜涯, Yinyeya, 生物科研狗, 做bench的伪生信攻城狮, 为了活着啥也干"
url: "https://www.xinlongluo.top"              # your host, for absolute URL
#baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
#weibo_username:     username
#zhihu_username:     username
github_username:    yinyeya
#twitter_username:   username
#facebook_username:  username
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]  



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: yinyeya

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-139612007-1'            # Format: UA-xxxxxx-xx
ga_domain: "https://www.xinlongluo.top"



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "For the next quantum leap<br>想避世更要在世上"
sidebar-avatar: /img/stand-under-sky.jpg     # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
#friends: [
#    {
#    #     title: "Su",
#    #     href: "http://su.gallery/"
#    # },{
#        title: "XXX",
#        href: "http://xxx/"
#    }
#]
